apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: election-sahayak
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      containers:
      - image: gcr.io/prompt-war-2026/election-sahayak:latest
        ports:
        - containerPort: 8080
